import type {
  AtRiskTaskReportResponse,
  LeaderboardUserResponse,
  ProgressTrendReportResponse,
  ProjectProgressReportResponse,
  RolePerformanceReportResponse,
  TaskBreakdownNode,
  UserPerformanceReportResponse,
  UserWorkloadHeatmapItem,
} from "@/types"

export const mockProjectProgress: ProjectProgressReportResponse = {
  projectId: 1,
  projectName: "NovaWorld Phan Thiết - Phân kỳ 1",
  totalTasks: 240,
  completedTasks: 185,
  completionRate: 77.1,
  totalParentTasks: 21,
  runningParentTasks: 7,
  totalChildTasks: 240,
  runningChildTasks: 55,
  zonesProgress: [
    {
      zoneId: 101,
      zoneName: "Khu A - Biệt thự biển Florida",
      totalTasks: 90,
      completedTasks: 72,
      completionRate: 80.0,
      totalParentTasks: 8,
      runningParentTasks: 2,
      totalChildTasks: 90,
      runningChildTasks: 18,
    },
    {
      zoneId: 102,
      zoneName: "Khu B - Sân Golf PGA Garden",
      totalTasks: 75,
      completedTasks: 58,
      completionRate: 77.3,
      totalParentTasks: 6,
      runningParentTasks: 2,
      totalChildTasks: 75,
      runningChildTasks: 17,
    },
    {
      zoneId: 103,
      zoneName: "Khu C - Công viên nước Circus Land",
      totalTasks: 75,
      completedTasks: 55,
      completionRate: 73.3,
      totalParentTasks: 7,
      runningParentTasks: 3,
      totalChildTasks: 75,
      runningChildTasks: 20,
    },
  ],
}

export const mockProgressTrend: ProgressTrendReportResponse = {
  projectId: 1,
  interval: "DAY",
  dataPoints: [
    {
      date: "09/10",
      plannedTasks: 15,
      actualCompletedTasks: 14,
      cumulativePlanned: 15,
      cumulativeActual: 14,
      completionRate: 93.3,
    },
    {
      date: "09/11",
      plannedTasks: 18,
      actualCompletedTasks: 17,
      cumulativePlanned: 33,
      cumulativeActual: 31,
      completionRate: 93.9,
    },
    {
      date: "09/12",
      plannedTasks: 20,
      actualCompletedTasks: 19,
      cumulativePlanned: 53,
      cumulativeActual: 50,
      completionRate: 94.3,
    },
    {
      date: "09/13",
      plannedTasks: 22,
      actualCompletedTasks: 20,
      cumulativePlanned: 75,
      cumulativeActual: 70,
      completionRate: 93.3,
    },
    {
      date: "09/14",
      plannedTasks: 16,
      actualCompletedTasks: 15,
      cumulativePlanned: 91,
      cumulativeActual: 85,
      completionRate: 93.4,
    },
    {
      date: "09/15",
      plannedTasks: 25,
      actualCompletedTasks: 21,
      cumulativePlanned: 116,
      cumulativeActual: 106,
      completionRate: 91.4,
    },
    {
      date: "09/16",
      plannedTasks: 24,
      actualCompletedTasks: 22,
      cumulativePlanned: 140,
      cumulativeActual: 128,
      completionRate: 91.4,
    },
    {
      date: "09/17",
      plannedTasks: 20,
      actualCompletedTasks: 18,
      cumulativePlanned: 160,
      cumulativeActual: 146,
      completionRate: 91.3,
    },
    {
      date: "09/18",
      plannedTasks: 22,
      actualCompletedTasks: 19,
      cumulativePlanned: 182,
      cumulativeActual: 165,
      completionRate: 90.7,
    },
    {
      date: "09/19",
      plannedTasks: 20,
      actualCompletedTasks: 17,
      cumulativePlanned: 202,
      cumulativeActual: 182,
      completionRate: 90.1,
    },
    {
      date: "09/20",
      plannedTasks: 18,
      actualCompletedTasks: 16,
      cumulativePlanned: 220,
      cumulativeActual: 198,
      completionRate: 90.0,
    },
    {
      date: "09/21",
      plannedTasks: 20,
      actualCompletedTasks: 17,
      cumulativePlanned: 240,
      cumulativeActual: 215,
      completionRate: 89.6,
    },
  ],
}

export const mockRolePerformance: RolePerformanceReportResponse[] = [
  {
    roleId: 1,
    roleName: "Trưởng BP Xây dựng",
    totalTasks: 42,
    completedTasks: 39,
    overdueTasks: 1,
    reworkTasks: 2,
    completionRate: 92.8,
  },
  {
    roleId: 2,
    roleName: "KSCC Giám sát Xây dựng",
    totalTasks: 65,
    completedTasks: 58,
    overdueTasks: 3,
    reworkTasks: 4,
    completionRate: 89.2,
  },
  {
    roleId: 3,
    roleName: "Trưởng BP Cơ điện",
    totalTasks: 38,
    completedTasks: 35,
    overdueTasks: 1,
    reworkTasks: 1,
    completionRate: 92.1,
  },
  {
    roleId: 4,
    roleName: "KSCC Giám sát Cơ điện",
    totalTasks: 52,
    completedTasks: 44,
    overdueTasks: 4,
    reworkTasks: 3,
    completionRate: 84.6,
  },
  {
    roleId: 5,
    roleName: "Trưởng BP Hạ tầng",
    totalTasks: 35,
    completedTasks: 31,
    overdueTasks: 2,
    reworkTasks: 2,
    completionRate: 88.5,
  },
  {
    roleId: 6,
    roleName: "KSCC Giám sát Hạ tầng",
    totalTasks: 48,
    completedTasks: 38,
    overdueTasks: 6,
    reworkTasks: 4,
    completionRate: 79.2,
  },
  {
    roleId: 7,
    roleName: "KSCC Kiểm soát ATLĐ",
    totalTasks: 56,
    completedTasks: 52,
    overdueTasks: 1,
    reworkTasks: 1,
    completionRate: 92.8,
  },
  {
    roleId: 8,
    roleName: "KSCC Kiểm soát QA/QC",
    totalTasks: 44,
    completedTasks: 36,
    overdueTasks: 5,
    reworkTasks: 3,
    completionRate: 81.8,
  },
  {
    roleId: 9,
    roleName: "KSCC Kiểm soát Trắc đạc",
    totalTasks: 30,
    completedTasks: 28,
    overdueTasks: 1,
    reworkTasks: 0,
    completionRate: 93.3,
  },
  {
    roleId: 10,
    roleName: "Kiến trúc sư Công trường",
    totalTasks: 26,
    completedTasks: 24,
    overdueTasks: 1,
    reworkTasks: 1,
    completionRate: 92.3,
  },
]

export const mockAtRiskTasks: AtRiskTaskReportResponse[] = [
  {
    taskInstanceId: 301,
    taskTitle: "Nghiệm thu lắp đặt ống thoát nước ngầm trục D3",
    parentTaskTitle: "Quản lý thi công hệ thống Hạ tầng kỹ thuật",
    zoneId: 101,
    zoneName: "Khu A - Biệt thự Florida",
    executorId: 101,
    executorName: "Nguyễn Văn Hùng",
    slaDeadline: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    minutesRemaining: 25,
    escalateLevel: "HIGH",
  },
  {
    taskInstanceId: 302,
    taskTitle: "Kiểm tra thép sàn tầng 3 Block B2 trước khi đổ bê tông",
    parentTaskTitle: "Đảm bảo chất lượng xây dựng công trình",
    zoneId: 102,
    zoneName: "Khu B - Sân Golf PGA",
    executorId: 102,
    executorName: "Trần Minh Đức",
    slaDeadline: new Date(Date.now() + 42 * 60 * 1000).toISOString(),
    minutesRemaining: 42,
    escalateLevel: "HIGH",
  },
  {
    taskInstanceId: 303,
    taskTitle: "Kiểm tra an toàn hệ thống giàn giáo ngoài khu vực rạp xiếc",
    parentTaskTitle: "Kiểm soát an toàn lao động và vệ sinh môi trường",
    zoneId: 103,
    zoneName: "Khu C - Circus Land",
    executorId: 103,
    executorName: "Lê Hoàng Nam",
    slaDeadline: new Date(Date.now() + 50 * 60 * 1000).toISOString(),
    minutesRemaining: 50,
    escalateLevel: "MEDIUM",
  },
  {
    taskInstanceId: 304,
    taskTitle: "Đo đạc kiểm tra tim trục định vị móng tháp chiếu sáng",
    parentTaskTitle: "Kiểm soát trắc đạc công trình",
    zoneId: 101,
    zoneName: "Khu A - Biệt thự Florida",
    executorId: 104,
    executorName: "Phạm Quốc Toàn",
    slaDeadline: new Date(Date.now() + 58 * 60 * 1000).toISOString(),
    minutesRemaining: 58,
    escalateLevel: "LOW",
  },
  {
    taskInstanceId: 305,
    taskTitle: "Nghiệm thu kéo cáp điện ngầm lộ nguồn trạm biến áp T2",
    parentTaskTitle: "Quản lý thi công hệ thống Cơ điện",
    zoneId: 102,
    zoneName: "Khu B - Sân Golf PGA",
    executorId: 105,
    executorName: "Đỗ Anh Tuấn",
    slaDeadline: new Date(Date.now() + 65 * 60 * 1000).toISOString(),
    minutesRemaining: 65,
    escalateLevel: "MEDIUM",
  },
]

export const mockLeaderboardUsers: LeaderboardUserResponse[] = [
  {
    rank: 1,
    userId: 101,
    userName: "Nguyễn Văn Hùng",
    roleName: "KSCC Giám sát Xây dựng",
    departmentName: "Phòng Quản lý Xây dựng",
    totalTasks: 84,
    onTimeTasks: 82,
    onTimeRate: 97.6,
    lateCompletedTasks: 1,
    lateRate: 1.2,
    uncompletedTasks: 1,
    uncompletedRate: 1.2,
    overdueTasks: 0,
    totalEarlyHours: 42.5,
  },
  {
    rank: 2,
    userId: 102,
    userName: "Trần Minh Đức",
    roleName: "KSCC Kiểm soát ATLĐ",
    departmentName: "Bộ phận An toàn & Môi trường",
    totalTasks: 78,
    onTimeTasks: 75,
    onTimeRate: 96.2,
    lateCompletedTasks: 2,
    lateRate: 2.5,
    uncompletedTasks: 1,
    uncompletedRate: 1.3,
    overdueTasks: 0,
    totalEarlyHours: 48.0,
  },
  {
    rank: 3,
    userId: 103,
    userName: "Lê Hoàng Nam",
    roleName: "KSCC Giám sát Cơ điện",
    departmentName: "Bộ phận Cơ điện",
    totalTasks: 72,
    onTimeTasks: 68,
    onTimeRate: 94.4,
    lateCompletedTasks: 3,
    lateRate: 4.2,
    uncompletedTasks: 1,
    uncompletedRate: 1.4,
    overdueTasks: 1,
    totalEarlyHours: 35.0,
  },
  {
    rank: 4,
    userId: 104,
    userName: "Phạm Quốc Toàn",
    roleName: "KSCC Kiểm soát Trắc đạc",
    departmentName: "Phòng Quản lý Xây dựng",
    totalTasks: 60,
    onTimeTasks: 56,
    onTimeRate: 93.3,
    lateCompletedTasks: 3,
    lateRate: 5.0,
    uncompletedTasks: 1,
    uncompletedRate: 1.7,
    overdueTasks: 1,
    totalEarlyHours: 28.0,
  },
  {
    rank: 5,
    userId: 105,
    userName: "Đỗ Anh Tuấn",
    roleName: "Trưởng BP Xây dựng",
    departmentName: "Phòng Quản lý Xây dựng",
    totalTasks: 95,
    onTimeTasks: 87,
    onTimeRate: 91.6,
    lateCompletedTasks: 6,
    lateRate: 6.3,
    uncompletedTasks: 2,
    uncompletedRate: 2.1,
    overdueTasks: 1,
    totalEarlyHours: 51.5,
  },
  {
    rank: 6,
    userId: 106,
    userName: "Vũ Đình Trọng",
    roleName: "KSCC Giám sát Hạ tầng",
    departmentName: "Bộ phận Hạ tầng",
    totalTasks: 64,
    onTimeTasks: 58,
    onTimeRate: 90.6,
    lateCompletedTasks: 4,
    lateRate: 6.3,
    uncompletedTasks: 2,
    uncompletedRate: 3.1,
    overdueTasks: 1,
    totalEarlyHours: 24.5,
  },
  {
    rank: 7,
    userId: 107,
    userName: "Bùi Thị Mai",
    roleName: "Kiến trúc sư Công trường",
    departmentName: "Phòng Quản lý Xây dựng",
    totalTasks: 48,
    onTimeTasks: 43,
    onTimeRate: 89.6,
    lateCompletedTasks: 4,
    lateRate: 8.3,
    uncompletedTasks: 1,
    uncompletedRate: 2.1,
    overdueTasks: 1,
    totalEarlyHours: 19.0,
  },
  {
    rank: 8,
    userId: 108,
    userName: "Hoàng Gia Bảo",
    roleName: "KSCC Kiểm soát QA/QC",
    departmentName: "Bộ phận QA/QC",
    totalTasks: 55,
    onTimeTasks: 47,
    onTimeRate: 85.5,
    lateCompletedTasks: 6,
    lateRate: 10.9,
    uncompletedTasks: 2,
    uncompletedRate: 3.6,
    overdueTasks: 2,
    totalEarlyHours: 16.0,
  },
  {
    rank: 9,
    userId: 109,
    userName: "Đặng Quang Huy",
    roleName: "KSCC Giám sát Cơ điện",
    departmentName: "Bộ phận Cơ điện",
    totalTasks: 88,
    onTimeTasks: 72,
    onTimeRate: 81.8,
    lateCompletedTasks: 12,
    lateRate: 13.6,
    uncompletedTasks: 4,
    uncompletedRate: 4.5,
    overdueTasks: 4,
    totalEarlyHours: 21.0,
  },
  {
    rank: 10,
    userId: 110,
    userName: "Ngô Tấn Lộc",
    roleName: "KSCC Giám sát Hạ tầng",
    departmentName: "Bộ phận Hạ tầng",
    totalTasks: 45,
    onTimeTasks: 35,
    onTimeRate: 77.8,
    lateCompletedTasks: 7,
    lateRate: 15.6,
    uncompletedTasks: 3,
    uncompletedRate: 6.7,
    overdueTasks: 3,
    totalEarlyHours: 11.5,
  },
]

export const mockUserPerformance: UserPerformanceReportResponse = {
  userId: 101,
  userName: "Nguyễn Văn Hùng",
  totalAssigned: 84,
  totalCompleted: 82,
  totalPassed: 80,
  totalFailed: 2,
  totalOverdue: 1,
  passRate: 97.6,
  completionRate: 97.6,
  totalParentTasks: 8,
  runningParentTasks: 1,
  totalChildTasks: 84,
  runningChildTasks: 2,
  lateTasks: 1,
  lateRate: 1.2,
  totalLateHours: 2.5,
  earlyTasks: 68,
  earlyRate: 81.0,
  totalEarlyHours: 42.5,
}

export const mockWorkloadHeatmap: UserWorkloadHeatmapItem[] = [
  { date: "2026-09-01", totalAssigned: 4, completedTasks: 4, overdueTasks: 0 },
  { date: "2026-09-02", totalAssigned: 5, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-03", totalAssigned: 4, completedTasks: 4, overdueTasks: 0 },
  { date: "2026-09-04", totalAssigned: 6, completedTasks: 6, overdueTasks: 0 },
  { date: "2026-09-05", totalAssigned: 3, completedTasks: 3, overdueTasks: 0 },
  { date: "2026-09-06", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-07", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-08", totalAssigned: 5, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-09", totalAssigned: 7, completedTasks: 7, overdueTasks: 0 },
  { date: "2026-09-10", totalAssigned: 6, completedTasks: 6, overdueTasks: 0 },
  { date: "2026-09-11", totalAssigned: 5, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-12", totalAssigned: 4, completedTasks: 4, overdueTasks: 0 },
  { date: "2026-09-13", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-14", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-15", totalAssigned: 8, completedTasks: 7, overdueTasks: 1 },
  { date: "2026-09-16", totalAssigned: 6, completedTasks: 6, overdueTasks: 0 },
  { date: "2026-09-17", totalAssigned: 5, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-18", totalAssigned: 5, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-19", totalAssigned: 4, completedTasks: 4, overdueTasks: 0 },
  { date: "2026-09-20", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-21", totalAssigned: 0, completedTasks: 0, overdueTasks: 0 },
  { date: "2026-09-22", totalAssigned: 6, completedTasks: 5, overdueTasks: 0 },
  { date: "2026-09-23", totalAssigned: 5, completedTasks: 2, overdueTasks: 0 },
]

export const mockUserTaskBreakdown: TaskBreakdownNode[] = [
  {
    id: 10,
    title: "1. Quản lý tiến độ thi công xây dựng",
    total: 32,
    completedTasks: 31,
    uncompletedTasks: 1,
    overdueTasks: 0,
    childTasks: [
      {
        id: 101,
        title: "1.1. Kiểm tra nhân lực, máy móc, vật tư thực tế của Nhà thầu",
        total: 14,
        completedTasks: 14,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
      {
        id: 102,
        title:
          "1.2. Kiểm tra tiến độ triển khai thực tế so với kế hoạch chi tiết",
        total: 12,
        completedTasks: 12,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
      {
        id: 103,
        title: "1.3. Phê duyệt tiến độ tuần / tháng của Nhà thầu",
        total: 6,
        completedTasks: 5,
        uncompletedTasks: 1,
        overdueTasks: 0,
        childTasks: [],
      },
    ],
  },
  {
    id: 20,
    title: "2. Đảm bảo chất lượng xây dựng công trình",
    total: 36,
    completedTasks: 35,
    uncompletedTasks: 1,
    overdueTasks: 1,
    childTasks: [
      {
        id: 201,
        title: "2.1. Tổ chức nghiệm thu vật tư, vật liệu trước khi sử dụng",
        total: 16,
        completedTasks: 16,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
      {
        id: 202,
        title:
          "2.2. Nghiệm thu công việc xây dựng trước khi chuyển bước thi công",
        total: 14,
        completedTasks: 13,
        uncompletedTasks: 1,
        overdueTasks: 1,
        childTasks: [],
      },
      {
        id: 203,
        title: "2.3. Xử lý khắc phục, theo dõi và đóng khiếm khuyết (Defect)",
        total: 6,
        completedTasks: 6,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
    ],
  },
  {
    id: 30,
    title: "3. Kiểm soát an toàn lao động và vệ sinh môi trường",
    total: 16,
    completedTasks: 16,
    uncompletedTasks: 0,
    overdueTasks: 0,
    childTasks: [
      {
        id: 301,
        title:
          "3.1. Kiểm tra điều kiện vệ sinh, ATLĐ khu vực thi công hàng ngày",
        total: 12,
        completedTasks: 12,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
      {
        id: 302,
        title: "3.2. Phê duyệt biện pháp an toàn trước khi thi công",
        total: 4,
        completedTasks: 4,
        uncompletedTasks: 0,
        overdueTasks: 0,
        childTasks: [],
      },
    ],
  },
]
