import React, { useState, useEffect } from "react"
import {
  Modal,
  Form,
  Input,
  Select,
  Row,
  Col,
  InputNumber,
  Typography,
  Card,
  Space,
  Tag,
  Divider,
  message,
} from "antd"
import {
  FilePlus2,
  CheckCircle,
  Copy,
  FolderGit2,
  Building,
  UserCheck,
  Layers,
} from "lucide-react"
import { DisciplineType, DocumentType, StageCode, DeliverableItem } from "../types"

const { Text } = Typography

interface RegisterDeliverableModalProps {
  open: boolean
  onClose: () => void
  onSuccess: (newDeliverable: DeliverableItem) => void
}

export const RegisterDeliverableModal: React.FC<RegisterDeliverableModalProps> = ({
  open,
  onClose,
  onSuccess,
}) => {
  const [form] = Form.useForm()

  // Các giá trị để tự động render Mã bản vẽ theo chuẩn REG01
  const [projectCode, setProjectCode] = useState("AQ")
  const [zoneCode, setZoneCode] = useState("PHX1")
  const [discipline, setDiscipline] = useState<DisciplineType>("ARC")
  const [docType, setDocType] = useState<DocumentType>("DWG")
  const [seqNumber, setSeqNumber] = useState(1)

  // Sinh mã tự động
  const formattedSeq = String(seqNumber).padStart(3, "0")
  const generatedCode = `${projectCode}-${zoneCode}-${discipline}-${docType}-${formattedSeq}`

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedCode)
    message.success(`Đã sao chép mã ${generatedCode}`)
  }

  const handleFinish = (values: any) => {
    const newItem: DeliverableItem = {
      id: `del-${Date.now()}`,
      projectCode,
      zoneCode,
      drawingCode: generatedCode,
      drawingName: values.drawingName,
      discipline,
      documentType: docType,
      stageCode: values.stageCode,
      stageName: getStageName(values.stageCode),
      packageCode: values.packageCode || `PKG-${discipline}-01`,
      scale: values.scale || "1/100",
      currentRevision: values.initialRevision || "Rev A",
      status: values.initialRevision === "Rev 0" ? "INTERNAL_REVIEW" : "DRAFT",
      leadConsultant: values.leadConsultant,
      verifierConsultant: values.verifierConsultant,
      dmdPic: values.dmdPic,
      dmdManager: "ThS.KTS. Nguyễn Phùng Hoàng An",
      sheetCount: values.sheetCount || 24,
      novagenCategory: values.novagenCategory || 7,
      novagenFolder: `/Novagen/${projectCode}/${zoneCode}/${values.stageCode}/${discipline}/`,
      handovers: [],
      revisions: [
        {
          revisionCode: values.initialRevision || "Rev A",
          versionNumber: 1,
          isCurrent: true,
          isAFC: false,
          releaseDate: new Date().toLocaleDateString("vi-VN"),
          author: values.leadConsultant,
          reviewer: values.dmdPic,
          changeReason: "Khởi tạo đăng ký hồ sơ thiết kế theo quy chuẩn NVLG-DMD-REG01",
          changeCategory: "INITIAL",
          fileName: `${generatedCode}_${values.initialRevision || "RevA"}.dwg`,
          fileSize: "42.0 MB",
          fileFormat: docType === "DWG" ? "DWG" : "PDF",
        },
      ],
      createdAt: new Date().toLocaleDateString("vi-VN"),
      updatedAt: new Date().toLocaleDateString("vi-VN"),
    }

    onSuccess(newItem)
    message.success(`Đăng ký thành công hồ sơ: ${generatedCode}`)
    form.resetFields()
    onClose()
  }

  const getStageName = (code: StageCode): string => {
    const map: Record<StageCode, string> = {
      G1: "1. Thiết kế Ý tưởng Quy hoạch",
      G2: "2. Thiết kế Quy hoạch Chi tiết 1/500",
      G3: "3. Thiết kế Ý tưởng Công trình (TKYT)",
      G4: "4. Thiết kế Cơ sở (TKCS)",
      G5: "5. Thiết kế Bản vẽ Thi công (2 bước)",
      G6: "6. Thiết kế Kỹ thuật (3 bước)",
      G7: "7. Thiết kế Bản vẽ Thi công (3 bước)",
      G8: "8. Bản vẽ Bán hàng & TTSP (SOP05)",
    }
    return map[code] || code
  }

  return (
    <Modal
      title={
        <div className="flex items-center gap-2">
          <FilePlus2 size={20} className="text-primary" />
          <span>Đăng Ký Hồ Sơ Bản Vẽ Mới (Chuẩn NVLG-DMD-REG01)</span>
        </div>
      }
      open={open}
      onCancel={onClose}
      onOk={() => form.submit()}
      okText="Xác Nhận Đăng Ký"
      cancelText="Hủy Bỏ"
      width={700}
      destroyOnClose
    >
      {/* Box preview mã số bản vẽ tự sinh */}
      <Card size="small" className="border-primary/40 bg-primary/5 my-3">
        <div className="text-xs text-muted-foreground uppercase font-semibold">
          Mã Số Bản Vẽ Dự Kiến (Auto-Generated by NVLG-DMD-REG01):
        </div>
        <div className="flex items-center justify-between mt-1">
          <div className="font-mono text-xl font-bold text-primary tracking-wide">
            {generatedCode}
          </div>
          <button
            type="button"
            onClick={handleCopyCode}
            className="flex items-center gap-1 text-xs px-2.5 py-1 bg-primary text-white rounded hover:bg-primary/90 transition-colors"
          >
            <Copy size={13} />
            Sao chép
          </button>
        </div>
        <div className="text-[11px] text-muted-foreground mt-1 flex items-center gap-1.5">
          <CheckCircle size={12} className="text-emerald-500" />
          Cấu trúc: [Dự án] - [Phân khu] - [Bộ môn] - [Loại tài liệu] - [Số thứ tự]
        </div>
      </Card>

      <Form
        form={form}
        layout="vertical"
        onFinish={handleFinish}
        initialValues={{
          projectCode: "AQ",
          zoneCode: "PHX1",
          discipline: "ARC",
          docType: "DWG",
          seqNumber: 1,
          stageCode: "G7",
          initialRevision: "Rev A",
          scale: "1/100",
          sheetCount: 24,
          novagenCategory: 7,
          dmdPic: "KTS. Hoàng Minh Trí",
          leadConsultant: "Aedas Architecture Ltd.",
        }}
      >
        <Divider titlePlacement="start" className="!text-xs !text-muted-foreground !my-2">
          1. Thông Tin Cấu Thành Mã Số (REG01)
        </Divider>

        <Row gutter={12}>
          <Col span={8}>
            <Form.Item label="Dự Án" required>
              <Select
                value={projectCode}
                onChange={setProjectCode}
                options={[
                  { value: "AQ", label: "AQ - Aqua City" },
                  { value: "NVW", label: "NVW - NovaWorld Phan Thiết" },
                  { value: "NVH", label: "NVH - NovaWorld Hồ Tràm" },
                  { value: "GLR", label: "GLR - The Grand Manhattan" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={8}>
            <Form.Item label="Phân Khu / Giai Đoạn" required>
              <Select
                value={zoneCode}
                onChange={setZoneCode}
                options={[
                  { value: "PHX1", label: "PHX1 - Phoenix 1A" },
                  { value: "PHX2", label: "PHX2 - Phoenix 2" },
                  { value: "STE", label: "STE - The Stella" },
                  { value: "VAL", label: "VAL - The Valencia" },
                  { value: "RVP", label: "RVP - River Park" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={8}>
            <Form.Item label="Bộ Môn (Discipline)" required>
              <Select
                value={discipline}
                onChange={(val) => setDiscipline(val as DisciplineType)}
                options={[
                  { value: "ARC", label: "ARC - Kiến trúc" },
                  { value: "STR", label: "STR - Kết cấu" },
                  { value: "MEP", label: "MEP - Cơ điện & PCCC" },
                  { value: "LND", label: "LND - Cảnh quan" },
                  { value: "INF", label: "INF - Hạ tầng kỹ thuật" },
                  { value: "PLN", label: "PLN - Quy hoạch đô thị" },
                  { value: "INT", label: "INT - Nội thất Fitout" },
                ]}
              />
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={12}>
          <Col span={12}>
            <Form.Item label="Loại Tài Liệu (Doc Type)" required>
              <Select
                value={docType}
                onChange={(val) => setDocType(val as DocumentType)}
                options={[
                  { value: "DWG", label: "DWG - Bản vẽ thiết kế" },
                  { value: "CAL", label: "CAL - Thuyết minh & Tính toán" },
                  { value: "BOQ", label: "BOQ - Bảng khối lượng" },
                  { value: "VER", label: "VER - Báo cáo thẩm tra TVTT" },
                  { value: "APP", label: "APP - Tờ trình phê duyệt AM" },
                  { value: "CR", label: "CR - Báo cáo thay đổi F02/F08" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={12}>
            <Form.Item label="Số Thứ Tự Bản Vẽ (Sequence)" required>
              <InputNumber
                min={1}
                max={999}
                value={seqNumber}
                onChange={(val) => setSeqNumber(val || 1)}
                className="w-full"
                placeholder="1, 2, 3..."
              />
            </Form.Item>
          </Col>
        </Row>

        <Divider titlePlacement="start" className="!text-xs !text-muted-foreground !my-2">
          2. Nội Dung Hồ Sơ & Đơn Vị Thực Hiện
        </Divider>

        <Form.Item
          name="drawingName"
          label="Tên Hồ Sơ / Bản Vẽ"
          rules={[{ required: true, message: "Vui lòng nhập tên hồ sơ" }]}
        >
          <Input placeholder="Ví dụ: Mặt bằng bố trí kết cấu dầm sàn tầng 1 - 3 Shophouse Dãy A2" />
        </Form.Item>

        <Row gutter={12}>
          <Col span={12}>
            <Form.Item
              name="stageCode"
              label="Giai Đoạn Quản Lý Thiết Kế (SOP09)"
              rules={[{ required: true }]}
            >
              <Select
                options={[
                  { value: "G1", label: "1. Thiết kế Ý tưởng Quy hoạch" },
                  { value: "G2", label: "2. Thiết kế Quy hoạch Chi tiết 1/500" },
                  { value: "G3", label: "3. Thiết kế Ý tưởng Công trình (TKYT)" },
                  { value: "G4", label: "4. Thiết kế Cơ sở (TKCS)" },
                  { value: "G5", label: "5. Thiết kế BVTC 2 bước" },
                  { value: "G6", label: "6. Thiết kế Kỹ thuật 3 bước" },
                  { value: "G7", label: "7. Thiết kế BVTC 3 bước" },
                  { value: "G8", label: "8. Bản vẽ Bán hàng & TTSP (SOP05)" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={12}>
            <Form.Item name="packageCode" label="Mã Gói Thầu">
              <Input placeholder="Ví dụ: PKG-ARC-01" />
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={12}>
          <Col span={12}>
            <Form.Item
              name="leadConsultant"
              label="Đơn Vị Tư Vấn Thiết Kế (TVTK)"
              rules={[{ required: true, message: "Vui lòng nhập tên TVTK" }]}
            >
              <Input placeholder="Aedas, Cotecons, Aurecon, SWA..." />
            </Form.Item>
          </Col>

          <Col span={12}>
            <Form.Item name="verifierConsultant" label="Đơn Vị Thẩm Tra Độc Lập (TVTT)">
              <Input placeholder="APAVE, IBST, SGS (nếu có)" />
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={12}>
          <Col span={8}>
            <Form.Item
              name="dmdPic"
              label="Chuyên Gia DMD Phụ Trách"
              rules={[{ required: true }]}
            >
              <Select
                options={[
                  { value: "KTS. Hoàng Minh Trí", label: "KTS. Hoàng Minh Trí (Kiến trúc)" },
                  { value: "KS. Vũ Đình Hùng", label: "KS. Vũ Đình Hùng (Kết cấu)" },
                  { value: "KS. Hoàng Quốc Tuấn", label: "KS. Hoàng Quốc Tuấn (MEP)" },
                  { value: "KTS. Lê Thị Quỳnh Mai", label: "KTS. Lê Thị Quỳnh Mai (Cảnh quan)" },
                  { value: "KS. Phạm Gia Bảo", label: "KS. Phạm Gia Bảo (Hạ tầng)" },
                  { value: "KTS. Lê Quang Minh", label: "KTS. Lê Quang Minh (Quy hoạch)" },
                  { value: "KTS. Đỗ Hoàng Yến", label: "KTS. Đỗ Hoàng Yến (Nội thất)" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={8}>
            <Form.Item name="initialRevision" label="Phiên Bản Khởi Tạo">
              <Select
                options={[
                  { value: "Rev A", label: "Rev A (Bản nháp nội bộ TVTK)" },
                  { value: "Rev B", label: "Rev B (Bản nháp vòng 2)" },
                  { value: "Rev 0", label: "Rev 0 (Trình duyệt chính thức AM)" },
                ]}
              />
            </Form.Item>
          </Col>

          <Col span={8}>
            <Form.Item name="novagenCategory" label="Đầu Mục Novagen (REG05)">
              <Select
                options={[
                  { value: 3, label: "03. Thiết kế Quy hoạch" },
                  { value: 4, label: "04. Thiết kế Ý tưởng (Concept)" },
                  { value: 5, label: "05. Thiết kế Cơ sở (TKCS)" },
                  { value: 6, label: "06. Thiết kế Kỹ thuật (TKKT)" },
                  { value: 7, label: "07. Bản vẽ Thi công (AFC)" },
                  { value: 8, label: "08. Bản vẽ Bán hàng (TTSP)" },
                  { value: 9, label: "09. Bản vẽ Hoàn công (As-Built)" },
                ]}
              />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}
